Vendor.Web/Areas/VendorService/Controllers/ManufacturingGroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Vendor.Datalayer;
using Vendor.Domain.Entites.Companies;

namespace Vendor.Web.Areas.VendorService.Controllers
{
    [Area("VendorService")]
    public class ManufacturingGroupsController : Controller
    {
        private readonly VendorDbContext _context;

        public ManufacturingGroupsController(VendorDbContext context)
        {
            _context = context;
        }

        // GET: VendorService/ManufacturingGroups
        public async Task<IActionResult> Index()
        {
            return View(await _context.ManufacturingGroups.ToListAsync());
        }

        // GET: VendorService/ManufacturingGroups/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manufacturingGroup = await _context.ManufacturingGroups
                .FirstOrDefaultAsync(m => m.Id == id);
            if (manufacturingGroup == null)
            {
                return NotFound();
            }

            return View(manufacturingGroup);
        }

        // GET: VendorService/ManufacturingGroups/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: VendorService/ManufacturingGroups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] ManufacturingGroup manufacturingGroup)
        {
            if (ModelState.IsValid)
            {
                _context.Add(manufacturingGroup);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(manufacturingGroup);
        }

        // GET: VendorService/ManufacturingGroups/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manufacturingGroup = await _context.ManufacturingGroups.FindAsync(id);
            if (manufacturingGroup == null)
            {
                return NotFound();
            }
            return View(manufacturingGroup);
        }

        // POST: VendorService/ManufacturingGroups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Name")] ManufacturingGroup manufacturingGroup)
        {
            if (id != manufacturingGroup.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(manufacturingGroup);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ManufacturingGroupExists(manufacturingGroup.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(manufacturingGroup);
        }

        // GET: VendorService/ManufacturingGroups/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manufacturingGroup = await _context.ManufacturingGroups
                .FirstOrDefaultAsync(m => m.Id == id);
            if (manufacturingGroup == null)
            {
                return NotFound();
            }

            return View(manufacturingGroup);
        }

        // POST: VendorService/ManufacturingGroups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var manufacturingGroup = await _context.ManufacturingGroups.FindAsync(id);
            _context.ManufacturingGroups.Remove(manufacturingGroup);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ManufacturingGroupExists(long id)
        {
            return _context.ManufacturingGroups.Any(e => e.Id == id);
        }
    }
}

Vendor.Web/Areas/VendorService/Views/ManufacturingGroups/Create.cshtml
@model Vendor.Domain.Entites.Companies.ManufacturingGroup

@{
    ViewData["Title"] = "افزودن";
    Layout = "";
}

<h4>افزودن</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Vendor.Web/Areas/VendorService/Views/ManufacturingGroups/Delete.cshtml
@model Vendor.Domain.Entites.Companies.ManufacturingGroup
@{
    ViewData["Title"] = "حذف";
    Layout = "";
}

<div class="row justify-content-lg-center">

    <div class="card col-lg-9">
        <div class="card-header">
            <div class="card-title-wrap bar-success mb-2 text-bold-700 font-size-1-3">
                حذف
            </div>
        </div>
        <!-- /.panel-heading -->
        <div class="card-body">
            <div class="text-right">
                <h3 class="font-size-0-9">
                    آیا از حذف مطمئن هستید؟
                </h3>
                <div class="col-md-12">
                    <form asp-action="Delete" method="post" class="text-left">
                        <input type="hidden" asp-for="Id" />
                        <a asp-action="Index" asp-route-id="@Model.Id" class="btn btn-sm font-size-0-9">بازگشت </a>
                        <input type="submit" value="حذف" class="btn btn-sm font-size-0-9 btn-outline-danger" />
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Vendor.Web/Areas/VendorService/Views/ManufacturingGroups/Edit.cshtml
@model Vendor.Domain.Entites.Companies.ManufacturingGroup


@{
    ViewData["Title"] = "ویرایش";
    Layout = "";
}


<h4>ویرایش</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="ذخیره" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Vendor.Web/Areas/VendorService/Views/ManufacturingGroups/Index.cshtml
@model IEnumerable<Vendor.Domain.Entites.Companies.ManufacturingGroup>
<section id="extended">
    <div class="row justify-content-lg-center">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title-wrap bar-success mb-2 text-bold-700 font-size-1-3">
                        نوع تولیدات شرکت
                    </div>
                </div>

                <div class="col-lg-12 container-fluid  text-right">
                    <a onclick="Add()" class="btn btn-outline btn-success font-size-0-9"><i class="fas fa-plus"></i> افزودن </a>
                </div>

                <div class="card-body m-3">
                    <div class="">
                        <table class="table table-responsive-md text-center table-bordered table-striped" id="mytable">
                            <thead class="thead-dark text-white">
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Id)
                                    </th>

                                    <th>
                                        @Html.DisplayNameFor(model => model.Name)
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Id)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Name)
                                        </td>
                                        <td>
                                            <a class="btn btn-sm btn-primary pull-right" onclick="Edit('@item.Id')">ویرایش</a> |
                                            <a class="btn btn-sm btn-danger pull-right" onclick="Del('@item.Id')"> حذف</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>

    function Add() {
            var SendingUrl = '@Url.Action("Create", "ManufacturingGroups")';
            $.get(SendingUrl,
                function (frmEdit) {
                    $("#itemEdit").html(frmEdit);
                    $("#edit-files").modal("show");

                });
        }

    function Edit(Id) {
            var SendingUrl = '@Url.Action("Edit", "ManufacturingGroups")';
        var SendingData = 'Id=' + Id ;
            $.get(SendingUrl,
                SendingData,
                function (frmEdit) {
                    $("#itemEdit").html(frmEdit);
                    $("#edit-files").modal("show");

                });
    }



    function Del(Id) {
            var SendingUrl = '@Url.Action("Delete", "ManufacturingGroups")';
        var SendingData = 'Id=' +Id;
            $.get(SendingUrl,
                SendingData,
                function (frmEdit) {
                    $("#itemEdit").html(frmEdit);
                    $("#edit-files").modal("show");

                });
        }


</script>